from string import ascii_lowercase, ascii_uppercase, digits

# Header info
DATA_LENGTH_LENGTH = 20
DATA_TYPE_LENGTH = 20
RECIPIENT_CODE_LENGTH = 10
HEADER_LENGTH = DATA_LENGTH_LENGTH + DATA_TYPE_LENGTH + RECIPIENT_CODE_LENGTH
HEADER_COMPONENTS = (DATA_LENGTH_LENGTH,DATA_TYPE_LENGTH,RECIPIENT_CODE_LENGTH)

# Alphanumeric string
CODE_CHARACTER_POOL = digits

# Server info
SERVER_CODE = "0000000000"
ALL_CODE = "9999999999"

# Admin Password
admin_password = "$argon2id$v=19$m=65536,t=3,p=4$i+nKuV7LawQnB8LogY5NkQ$640d6+UiGUR704021yy4mrREDQPD4DLfSzCIhQ1DlWE"
