from string import digits

# Header info
DATA_LENGTH_LENGTH = 20
DATA_TYPE_LENGTH = 20
RECIPIENT_CODE_LENGTH = 10
HEADER_LENGTH = DATA_LENGTH_LENGTH + DATA_TYPE_LENGTH + RECIPIENT_CODE_LENGTH
HEADER_COMPONENTS = (DATA_LENGTH_LENGTH,DATA_TYPE_LENGTH,RECIPIENT_CODE_LENGTH)

# Alphanumeric string
CODE_CHARACTER_POOL = digits

# Server info
SERVER_CODE = "0000000000"
ALL_CODE = "9999999999"

# Admin Password
ADMIN_PASSWORD = "$argon2id$v=19$m=65536,t=3,p=4$8tnirUc7eFY9nygch1e78Q$GskXqUprg0HZJs6MMK2kv/3jGmsNiqDEIx+H4JCfv5E"

PICKLED_DATA_TYPES = ("CONNECT_ACCEPT", "CONTROL_EVENT", "DB_LOGS", "DB_USERS")
